name: PROJECT_NAME
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  # BLAS choice explicit (great on Ryzen)
  # - libblas=*=*openblas
  # * Pytorch no longer publishes conda packages after pytorch v2.5.1, so install these with pip instead:
  # - pytorch::pytorch=2.4.0
  # - pytorch::pytorch-cuda=12.1
  # - pytorch::torchvision=0.19.0
  - cython # Some pip builds use this
  - pandas[performance,plot,output-formatting]
  # * To speed up pandas: numexpr bottleneck numba
  - numexpr
  - bottleneck
  - numba
  # * Most of the rest of these are heavier compiled libs that are better installed via conda/mamba than pip:
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - setuptools
  - pyarrow
  - libzlib
  - zstd
  - libjpeg-turbo
  - libpng
  - lz4
  - pycocotools
  - wheel
  - pip:
      - -c constraints.txt
      - -r requirements.txt
